name: run-unit-tests
on: 
  push:
    tags:
      - "v[0-9]+.[0-60]+_dev"
      - "v[0-9]+.[0-60]+_prod"

permissions:
  id-token: write
  contents: read

jobs:
  check_tag_environment:
    uses: ./.github/workflows/check-env.yml
    secrets: inherit
  
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 1   
           
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py await_db && python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"